### ISSUE TITLE
Installation fails when you try to opt-out Code Ready (che) passing extra-vars

### ISSUE THREAD

**Issue by rafaeltuelho** [integr8ly/installation#1027]
## Description
If you try to opt-out `che` component the playbook fails in a couple of points:
1. to test `when` clauses due the lack of cast to `bool`
2. the `msbroker` role tries to get the che dashboard url even if you opt-out che installation

## Expected Behavior
install Playbook che role should properly handle `che` variable...

## Actual Behavior
1. `when: che` clauses without cast to `bool` type

in `roles/msbroker/tasks/apply_msbroker_template.yml`
```
- name: Get Che dashboard url
  shell: oc get route/codeready -o jsonpath='{.spec.host}' -n {{ eval_che_namespace }}
  register: che_host_cmd
  when: che and launcher
- set_fact:
    che_dashboard_url: "https://{{ che_host_cmd.stdout}}"
  when: che and launcher
```

2. TASK [msbroker : Get Che dashboard url] failing

```
TASK [msbroker : Get Che dashboard url] *******************************************************************************************************************************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": true, "cmd": "oc get route/codeready -o jsonpath='{.spec.host}' -n integr8tly-codeready", "delta": "0:00:00.188786", "end": "2019-09-24 14:21:30.138528", "msg": "non-zero return code", "rc": 1, "start": "2019-09-24 14:21:29.949742", "stderr": "Error from server (NotFound): namespaces \"integr8tly-codeready\" not found", "stderr_lines": ["Error from server (NotFound): namespaces \"integr8tly-codeready\" not found"], "stdout": "", "stdout_lines": []}
```

## Environment

* Operating system: RHEL 7.6 
* OpenShift version: 3.11.104
```
oc v3.11.104
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://master1.tjpe-fef2.internal:443
openshift v3.11.104
kubernetes v1.11.0+d4cacc0
```

* Ansible version:
```
ansible 2.6.18
  config file = /root/integr8tly/installation/ansible.cfg
  configured module search path = [u'/root/integr8tly/installation/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 12:19:05) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

* Project Version/Tag: (E.g release-1.0.1)

## Steps to reproduce
1. run the install playbook passing `-e che=False`
