### ISSUE TITLE
enable wildcard route on router

### ISSUE THREAD

**Issue by yithian** [integr8ly/installation#552]
## Description
The installer should configure the secondary router with a 3scale wildcard route and superdomain.

## Expected Behavior
The installer:
- configures a 3scale wildcard route on the second (3amp) router:
```
apiVersion: route.openshift.io/v1
kind: Route
metadata:
 labels:
   3scale.component: apicast
   3scale.component-element: wildcard-router
   app: 3scale-api-management
 name: apicast-wildcard-router-routing-shard
spec:
 host: wildcard.${CLUSTER}.${DOMAIN}.${TLD}
 port:
   targetPort: http
 tls:
   termination: edge
 to:
   kind: Service
   name: apicast-wildcard-router
   weight: 100
 wildcardPolicy: Subdomain
```
- sets `ROUTER_ALLOW_WILDCARD_ROUTES=true` on the secondary (3amp) router
- sets `{\"data\":{\"THREESCALE_SUPERDOMAIN\": \"3amp.${CLUSTER}.${DOMAIN}.${TLD}\"}}` on the system-environment configmap and ensures that the changes are rolled out

## Actual Behavior
None of those things happen.

## Environment

* Operating system: (E.g RHEL 7.6 )
Red Hat Enterprise Linux Server release 7.5 (Maipo)

* OpenShift version:
oc v3.11.43
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://internal.api.integreatly-phx.openshift.com:443
openshift v3.11.43
kubernetes v1.11.0+d4cacc0

* Ansible version:
ansible 2.7.1

* Project Version/Tag: (E.g release-1.0.1)
release-1.3.0

## Steps to reproduce
run the installer
