### ISSUE TITLE
The xml ansible module requires the lxml python library installed on the managed machine

### ISSUE THREAD

**Issue by pb82** [integr8ly/installation#95]
The 3scale role reports this error: 

```
TASK [3scale : Get user ID: evals@example.com] ********************************************************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "The xml ansible module requires the lxml python library installed on the managed machine"}
```

It still continues because the error is ignored:

```yaml
- name: "Get user ID: {{ username }}"
  xml:
    path: /tmp/3scale_users.xml
    xpath: /users/user[email[text()='{{ email }}']]/id
    content: text
  register: eval_user_xml
  ignore_errors: True
```

but then the role fails in the `Create user` step with:

```json
 {"errors": {"email": ["has already been taken"], "username": ["has already been taken"]}}
```
